import develope

develope.add_audio('配信用','とぅぎっ２')
develope.add_audio('配信用','ﾄｩｷﾞｯ')
develope.add_audio('配信用','ﾄｩｷﾞｯ2')
develope.add_audio('配信用','うんこしまってください')
develope.add_audio('配信用','うんこはじめてぇ？')
develope.add_audio('配信用','かいべんかいべ～ん')
develope.add_audio('配信用','キレイな巻糞ですぅ')
develope.add_audio('配信用','戻してくださいお尻に')
develope.add_audio('配信用','シンプル排泄')
develope.add_audio('配信用','スパチャだぁいすきぃぃ')
develope.add_audio('配信用','一等賞だよ！ない🍑！')
develope.add_audio('配信用','マゼンタ混ぜ混ぜ！キュアマゼンタ!!')
develope.add_audio('配信用','ブrrrrrrrrrァボー')
develope.add_audio('配信用','ねこちゃん')
develope.add_audio('配信用','ねっこちゃん')
develope.add_audio('配信用','ね！こちゃん')
develope.add_audio('配信用','ﾈｺﾁｬﾝ')
develope.add_audio('配信用','ねこちゃんないすて')
develope.add_audio('配信用','ねっこちゃんないすて')
develope.add_audio('配信用','うん')
develope.add_audio('配信用','ちょこ')
develope.add_audio('配信用','ちょこちょこ')
develope.add_audio('配信用','ぴーーー')
develope.add_audio('配信用','うんちょこちょこちょこぴー')
develope.add_audio('配信用','パン')
develope.add_audio('配信用','パカ')
develope.add_audio('配信用','ピー')
develope.add_audio('配信用','プー')
develope.add_audio('配信用','まぁまぁまぁ、その話は一旦置いといて')
develope.add_audio('配信用','ドラムロール')
develope.add_audio('配信用','ユニコォォォン!!')
#develope.del_audio('モノマネ','目覚ましボイス')
#develope.change_audio('配信用','（よろしくお願いします）','クソ.mp3')
#init_lang_file()